spring:
  datasource:
    url: jdbc:postgresql://localhost:15433/waiting_machine
    username: user
    password: pass
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    db:
      enabled: true
