{
 "title": "Waiting Machine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"host.docker.internal:8080\"}"
    }
   ]
  },
  {
   "title": "Scheduler Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "changes(overcrowd_situation_total[2m])",
     "legendFormat": "overcrowd_situation"
    }
   ]
  },
  {
   "title": "API response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(irate(http_server_requests_seconds_sum{uri!~\".*/actuator/.*\", status=~\"[2]..\"}[2m])) by (uri)) / sum(irate(http_server_requests_seconds_count{uri!~\".*/actuator/.*\", status=~\"[2]..\"}[2m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "API Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{status=~\"[5]..\"}[2m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Database IO speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(spring_data_repository_invocations_seconds_sum{state=\"SUCCESS\"}[2m]) /\r\nirate(spring_data_repository_invocations_seconds_count{state=\"SUCCESS\"}[2m])",
     "legendFormat": "{{repository}} - {{method}}"
    }
   ]
  },
  {
   "title": "Database IO Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(spring_data_repository_invocations_seconds_count{state!=\"SUCCESS\"}[2m])) by (repository, method)",
     "legendFormat": "{{repository}} - {{method}}"
    }
   ]
  }
 ]
}